"""Central registry of Rally org deployments.

This is the single source of truth for what makes each org's deployment
different (volume path, admin emails, pillar list, Box folder, branding).
Both the interactive app and the Workflow jobs (`reminders.py`,
`weekly_status_digest.py`, `rollups_job.py`) call `apply_env_defaults()`
before importing `config`/`pillars`/`storage`, so `os.environ.setdefault(...)`
picks up the right org's values regardless of what the Databricks App/Job
runtime injects.

Adding a new org means adding one entry here (plus its own
`orgs/<org_id>/pillars.json`) — no other file needs to change.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field

DEFAULT_ORG_ID = "pase"

DATABRICKS_HOST = "https://nike-sole-react-3.cloud.databricks.com"
MODEL_ENDPOINT = "databricks-claude-sonnet-4-6"


@dataclass(frozen=True)
class OrgConfig:
    org_id: str
    label: str
    volume_path: str
    admin_emails: str  # comma-separated, matches PASE_TRACKER_ADMIN_EMAILS format
    pillars_file: str  # path relative to repo root
    box_root_folder_id: str
    box_mirror_enabled: str = "1"
    box_folder_link: str = ""
    summary_footer: str = ""
    app_url: str = ""
    extra_env: dict[str, str] = field(default_factory=dict)


ORGS: dict[str, OrgConfig] = {
    "pase": OrgConfig(
        org_id="pase",
        label="PaSE",
        volume_path="/Volumes/development/team_na_pase_process_intelligence/pase_work_tracker",
        admin_emails="Spencer.Stendel@nike.com,Evan.Horne@nike.com",
        pillars_file="orgs/pase/pillars.json",
        box_root_folder_id="397702842180",
        box_folder_link="https://nike.box.com/s/m7435ld1srodd92ck28qaid6j5nd7h6j",
        summary_footer="Generated by Rally · Process & Solutions Enablement",
        app_url="https://pase-work-tracker-7474649843005973.aws.databricksapps.com/",
    ),
    "scpo": OrgConfig(
        org_id="scpo",
        label="SCPO Process Excellence",
        # Lives in the same UC schema as PaSE (team_na_pase_process_intelligence)
        # as its own dedicated volume — no new Nike team/schema registration
        # needed. Data isolation is at the volume level: MeetingStorage only
        # ever reads/writes within PASE_TRACKER_VOLUME, so this never crosses
        # into PaSE's pase_work_tracker volume.
        volume_path="/Volumes/development/team_na_pase_process_intelligence/scpo_process_excellence",
        admin_emails="Stacey.McQuain@nike.com,Monica.Buys@nike.com,Spencer.Stendel@nike.com,Evan.Horne@nike.com",
        pillars_file="orgs/scpo/pillars.json",
        # Placeholder "SCPO Process Excellence" folder (currently nested under
        # PaSE's own "Process Intelligence" Box tree) — Stacey's team will move
        # it to its permanent home later; this id stays valid across the move.
        # There's also a separate, older "SCPO Process Excellence" folder
        # (id 288161062942, maintained by Stacey McQuain since Oct 2024) — do
        # NOT use that one here, it's a different folder.
        # IMPORTANT: the shared Rally Box JWT service account
        # (AutomationUser_2623638_gnqC2bQGTb@boxdevedition.com) is NOT yet a
        # collaborator on this folder — Spencer is adding it as an Editor.
        # Flip box_mirror_enabled to "1" once that's confirmed working.
        box_root_folder_id="405887869871",
        box_mirror_enabled="0",
                    box_folder_link="https://nike.box.com/folder/405887869871",
                    summary_footer="Generated by Rally · SCPO Process Excellence",
                    app_url="https://scpo-process-excellence-7474649843005973.aws.databricksapps.com/",
                    extra_env={
                        # weekly_status_digest.py's Friday "who hasn't submitted"
                        # DM — defaults to Spencer for PaSE; SCPO wants it to go
                        # to its own leads instead (comma-separated for multiple).
                        "RALLY_DIGEST_RECIPIENT": "Stacey.McQuain@nike.com,Monica.Buys@nike.com,Erin.Bestkuenzel@nike.com,Jennifer.Maslen@nike.com",
                    },
                ),
}


def _org_id_from_argv() -> str | None:
    """Serverless Databricks Jobs (spark_python_task) don't support setting
    env vars directly in databricks.yml, only `parameters` (argv). Each org's
    job resources pass `parameters: ["RALLY_ORG=<org_id>"]` so one shared
    script (reminders.py, etc.) can serve every org."""
    for arg in sys.argv[1:]:
        if arg.startswith("RALLY_ORG="):
            return arg.split("=", 1)[1].strip()
    return None


def get_org(org_id: str | None = None) -> OrgConfig:
    org_id = org_id or os.getenv("RALLY_ORG") or _org_id_from_argv() or DEFAULT_ORG_ID
    return ORGS.get(org_id, ORGS[DEFAULT_ORG_ID])


def apply_env_defaults(org_id: str | None = None) -> OrgConfig:
    """Set os.environ defaults for this org's deployment.

    Must be called before importing `config`, `pillars`, or `storage` in any
    entrypoint (app.py, reminders.py, weekly_status_digest.py, rollups_job.py)
    so `get_settings()` resolves the right volume/host regardless of what the
    Databricks App/Job runtime injects. Uses `setdefault` throughout so any
    env var explicitly set by the deployment (app.yaml / databricks.yml)
    still wins.
    """
    org = get_org(org_id)
    os.environ.setdefault("RALLY_ORG", org.org_id)
    os.environ.setdefault("DATABRICKS_HOST", DATABRICKS_HOST)
    os.environ.setdefault("DATABRICKS_MODEL_ENDPOINT", MODEL_ENDPOINT)
    os.environ.setdefault("PASE_TRACKER_VOLUME", org.volume_path)
    os.environ.setdefault("PASE_TRACKER_ADMIN_EMAILS", org.admin_emails)
    os.environ.setdefault("RALLY_ORG_LABEL", org.label)
    os.environ.setdefault("RALLY_PILLARS_CONFIG", org.pillars_file)
    os.environ.setdefault("PASE_TRACKER_BOX_ROOT_FOLDER_ID", org.box_root_folder_id)
    os.environ.setdefault("PASE_TRACKER_BOX_MIRROR_ENABLED", org.box_mirror_enabled)
    if org.box_folder_link:
        os.environ.setdefault("PASE_TRACKER_BOX_FOLDER_LINK", org.box_folder_link)
    if org.summary_footer:
        os.environ.setdefault("SUMMARY_FOOTER", org.summary_footer)
    if org.app_url:
        os.environ.setdefault("RALLY_APP_URL", org.app_url)
    for key, value in org.extra_env.items():
        os.environ.setdefault(key, value)
    return org
