"""One-time local setup: push the Box dev JWT app credentials into the
existing `pase-work-tracker` Databricks secret scope.

Run this LOCALLY (not on Databricks) — it shells out to the `databricks`
CLI using your own `.databrickscfg` auth, the same way `deploy.sh` does.

Usage:
    python3 setup/store_box_dev_secrets.py /path/to/box_jwt_config.json

The JSON is the "Download as JSON" config generated by the Box Developer
Console for the JWT app (top-level `boxAppSettings` + `enterpriseID`).
This script only reads it locally and never prints or logs any of its
secret fields — each value is piped to `databricks secrets put-secret`
via stdin so it never appears in shell history or process args.

Existing keys in scope `pase-work-tracker` (slack-bot-token,
databricks-token) are untouched; secret scopes are indexed by
(scope, key), so adding new box-dev-* keys is purely additive.
"""

from __future__ import annotations

import json
import subprocess
import sys

SCOPE = "pase-work-tracker"
PROFILE = "DEFAULT"
DATABRICKS_CLI = "databricks"  # resolved via PATH; deploy.sh uses ~/.local/bin/databricks explicitly if needed

# (secret key name, path into the JSON as a list of nested keys)
FIELDS: list[tuple[str, list[str]]] = [
    ("box-dev-client-id", ["boxAppSettings", "clientID"]),
    ("box-dev-client-secret", ["boxAppSettings", "clientSecret"]),
    ("box-dev-public-key-id", ["boxAppSettings", "appAuth", "publicKeyID"]),
    ("box-dev-private-key", ["boxAppSettings", "appAuth", "privateKey"]),
    ("box-dev-passphrase", ["boxAppSettings", "appAuth", "passphrase"]),
    ("box-dev-enterprise-id", ["enterpriseID"]),
]


def _dig(data: dict, path: list[str]) -> str:
    node = data
    for key in path:
        node = node[key]
    return str(node)


def _put_secret(key: str, value: str) -> None:
    """Write one secret via stdin so the value never touches argv or history.

    The CLI reads the secret value from stdin (supports multi-line, e.g. the
    PEM private key) whenever neither --string-value nor --bytes-value is
    passed.
    """
    subprocess.run(
        [DATABRICKS_CLI, "secrets", "put-secret", SCOPE, key, "--profile", PROFILE],
        input=value.encode("utf-8"),
        check=True,
    )
    print(f"  wrote {key} ({len(value)} chars)")


def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: python3 setup/store_box_dev_secrets.py /path/to/box_jwt_config.json")
        sys.exit(1)

    config_path = sys.argv[1]
    with open(config_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    missing = [key for key, path in FIELDS if not _dig(config, path)]
    if missing:
        print(f"Config is missing expected fields for: {missing}")
        sys.exit(1)

    print(f"Writing 6 secrets into scope '{SCOPE}'...")
    for key, path in FIELDS:
        value = _dig(config, path)
        _put_secret(key, value)

    print(
        "\nDone. Existing keys in this scope (slack-bot-token, databricks-token) "
        "are unaffected — only the 6 box-dev-* keys above were added/updated."
    )


if __name__ == "__main__":
    main()
